# fly.toml app configuration file generated for nk-movie-scraper on 2025-05-27T17:05:11+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nk-movie-scraper'
primary_region = 'hkg'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "storage"
destination = "/storage"
